services:
  graphite_exporter:
    image: prom/graphite-exporter:latest
    container_name: graphite_exporter
    ports:
      - "9108:9108"
      - "2003:2003"
    volumes:
      - ./graphite_mappings.yaml:/etc/graphite_mappings.yaml
    command: --graphite.mapping-config=/etc/graphite_mappings.yaml --graphite.listen-address=:2003
